# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_sservice_name", "plain_value", "%parameter_name%"]
    ens.benjamin.admin.category:
        class: Ens\BenjaminBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Categories }
        arguments: [null, Ens\BenjaminBundle\Entity\Category, EnsBenjaminBundle:CategoryAdmin]

    ens.benjamin.admin.job:
        class: Ens\BenjaminBundle\Admin\JobAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Jobs }
        arguments: [null, Ens\BenjaminBundle\Entity\Job, EnsBenjaminBundle:jobadmin]
