# src/Ens/BenjaminBundle/Resources/config/routing.yml
EnsBenjaminBundle_job:
    resource: "@EnsBenjaminBundle/Resources/config/routing/job.yml"
    prefix: /job
 
EnsBenjaminBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: EnsBenjaminBundle:Default:index }