# src/Ens/BenjaminBundle/Resources/config/routing.yml
EnsBenjaminBundle_job:
    resource: "@EnsBenjaminBundle/Resources/config/routing/job.yml"
    prefix: /job

EnsBenjaminBundle_homepage:
    path:  /
    defaults: { _controller: EnsBenjaminBundle:Job:index }

EnsBenjaminBundle_category:
    path: /category/{slug}/{page}
    defaults: { _controller: EnsBenjaminBundle:Category:show, page: 1 }
